oplus_touchscreen_v2: Fix unused variable warning
drivers/input/touchscreen/oplus_touchscreen_v2/ilitek/ilitek7807s/ili7807s_fw.c:529:6:
error: variable 'ges_area_section' set but not used
[-Werror,-Wunused-but-set-variable]
	u32 ges_area_section = 0, ges_info_addr = 0, ges_fw_start = 0,
ges_fw_end = 0;
	    ^
drivers/input/touchscreen/oplus_touchscreen_v2/ilitek/ilitek7807s/ili7807s_node.c:2701:13:
error: variable 'ret' set but not used [-Werror,
-Wunused-but-set-variable]
	int i = 0, ret = 0;
		   ^
2 errors generated.

Change-Id: I922426745980d65c50badfedc7d8aa7dc3e043f1